---
title: "PulliamAirportWeatherDemo"
author: "Nathan Underwood"
date: "`r Sys.Date()`"
output: html_document
---

```{r Initialization, warning = FALSE, message = FALSE}
library(ggplot2)
library(latex2exp)
library(tidyverse)
library(UnderwoodChapter16)
```


```{r Snowfall in Inches in Flagstaff in February 2019, message = FALSE}
PulliamAirportWeather2019 <- PulliamAirportWeather %>% 
  filter(year(date) == 2019 & month(date) == 2) %>% 
  mutate(day = day(date))

ggplot(PulliamAirportWeather2019, aes(x = day, y = snow)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(5, 25, by = 5), minor_breaks = 1:28 ) +
  labs(title = "Snowfall in Inches in Flagstaff in February 2019") +
  labs(x = "February", y = "Snowfall (in)")
```

```{r Range of Minimum and Maximum Temperatures in Flagstaff During August 2000, message = FALSE}
PulliamAirportWeather2000 <- PulliamAirportWeather %>% 
  filter(year(date) == 2000 & month(date) == 8) %>% 
  mutate(day = day(date))

ggplot(PulliamAirportWeather2000, aes(x = day, y = tmin)) +
  geom_ribbon(aes(ymin = tmin, ymax = tmax), fill = "aquamarine3") +
  scale_x_continuous(breaks = seq(5, 30, by = 5), minor_breaks = 1:31 ) +
  labs(title = "Range of Minimum and Maximum Temperatures in Flagstaff During August 2000") +
  labs(x = "August", y = "Temperature (\u00B0F)")
```
